
SET TERMOUT ON
PROMPT Building demonstration tables.  Please wait.
SET TERMOUT OFF

DROP TABLE HOTEL;
DROP TABLE ROOM;
DROP TABLE BOOMNUMBER;
DROP TABLE BOOKING;
DROP TABLE CUSTOMER;
DROP TABLE ROOMTYPE;
DROP TABLE GUEST;

CREATE TABLE HOTEL
(
	NORA NUMBER(100) NOT NULL,
    	NORC NUMBER(3)
);

CREATE TABLE ROOM
    (ROOMTYPE VARCHAR(10) NOT NULL,
    BASICPRICE NUMBER(4),
    ROOMCAP NUMBER(2));

CREATE TABLE ROOMTYPE
    (ROOMNUM NUMBER(2),
    ROOMTYPE VARCHAR(10));

CREATE TABLE ROOMNUMBER
    (ROOMNUM NUMBER(2),
    ROOMAVAIL NUMBER(1));

CREATE TABLE BOOKING
    (BID VARCHAR(10) NOT NULL,
    CID VARCHAR(10) NOT NULL,
    ROOMNUM NUMBER(3) NOT NUll,
    CDATE DATE(),
    NOG NUMBER(1));

CREATE TABLE CUSTOMER
    (CID VARCHAR(10) NOT NULL,
    BID VARCHAR(10) NOT NULL);

CREATE TABLE GUEST
    (GID VARCHAR(10) NOT NULL,
    FNAME VARCHAR(),
    LNAME VARCHAR(),
    AGROUP NUMBER(1),
    BID VARCHAR(10) NOT NULL);

INSERT INTO HOTEL (NORA, NORC) VALUES (100, 0);

COMMIT;

SET TERMOUT ON
PROMPT Demonstration table build is complete.
