SET TERMOUT ON
PROMPT Building demonstration tables.  Please wait.

DROP TABLE HOTEL;
DROP TABLE GUEST;
DROP TABLE CUSTOMER;
DROP TABLE BOOKING;
DROP TABLE ROOM;
DROP TABLE ROOMNUMBER;
DROP TABLE ROOMTYPE;

CREATE TABLE HOTEL
	(NORA NUMBER(3) NOT NULL,
	NORC NUMBER(3));

CREATE TABLE ROOMTYPE
    (ROOMNUM NUMBER(3) UNIQUE,
    ROOMTYPE VARCHAR(10));

CREATE TABLE ROOM
    (ROOMNUM NUMBER(3) REFERENCES ROOMTYPE(ROOMNUM),
    BASICPRICE NUMBER(4),
    ROOMCAP NUMBER(2));

CREATE TABLE ROOMNUMBER
    (ROOMNUM NUMBER(3) REFERENCES ROOMTYPE(ROOMNUM),
    ROOMAVAIL NUMBER(2)); 

CREATE TABLE GUEST
    (GID VARCHAR(10),
    FNAME VARCHAR(20),
    LNAME VARCHAR(20),
    AGROUP NUMBER(1),

CREATE TABLE BOOKING
    (BID VARCHAR(10) PRIMARY KEY,
    GID VARCHAR(10) REFERENCES GUEST(GID) NOT NULL,
    ROOMNUM NUMBER(3) REFERENCES ROOMTYPE(ROOMNUM) NOT NUll,
    CDATE DATE,
    NOG NUMBER(1));

INSERT INTO HOTEL (NORA, NORC) VALUES (100, 0);

BEGIN
  FOR count IN 1..33 LOOP
    INSERT INTO ROOMTYPE (ROOMNUM, ROOMTYPE) VALUES (count, 'superior');
    INSERT INTO ROOM (ROOMNUM, BASICPRICE, ROOMCAP) VALUES (count, 170, 3);
  END LOOP;
END;
/
BEGIN
  FOR i IN 34..66 LOOP
    INSERT INTO ROOMTYPE (ROOMNUM, ROOMTYPE) VALUES (i, 'deluxe');
    INSERT INTO ROOM (ROOMNUM, BASICPRICE, ROOMCAP) VALUES (i, 200, 2);
  END LOOP;
END;
/
BEGIN
  FOR j IN 67..100 LOOP
    INSERT INTO ROOMTYPE (ROOMNUM, ROOMTYPE) VALUES (j, 'basic');
    INSERT INTO ROOM (ROOMNUM, BASICPRICE, ROOMCAP) VALUES (j, 100, 2);
  END LOOP;
END;
/
BEGIN
  FOR k IN 1..50 LOOP
    INSERT INTO ROOMNUMBER (ROOMNUM, ROOMAVAIL) VALUES (k, 1);
  END LOOP;
END;
/
BEGIN
  FOR p IN 51..100 LOOP
    INSERT INTO ROOMNUMBER (ROOMNUM, ROOMAVAIL) VALUES (p, 0);
  END LOOP;
END;
/

CREATE SEQUENCE BOOKING_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE GUEST_ID START WITH 1 INCREMENT BY 1;

/**/
INSERT INTO GUEST (GID, FNAME, LNAME, AGROUP)
  VALUES(GUEST_ID.NEXTVAL, 'Markita', 'Risko', 1);
INSERT INTO GUEST (GID, FNAME, LNAME, AGROUP)
  VALUES(GUEST_ID.VAL, 'Ivette', 'Lundberg', 2);
INSERT INTO GUEST (GID, FNAME, LNAME, AGROUP)
  VALUES(GUEST_ID.VAL, 'Era', 'Brito', 3);
INSERT INTO GUEST (GID, FNAME, LNAME, AGROUP)
  VALUES(GUEST_ID.NEXTVAL, 'Lavone', 'Dore', 1);

/*CHECKIN DATE BEFORE TODAY*/
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 1, TO_DATE('2010/03/30', 'yyyy/mm/dd'), 3);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 2, TO_DATE('2012/04/01', 'yyyy/mm/dd'), 3);

/* CHECKIN DATE TODAY -> */

/*3 GUESTS, SUPERIOR ROOM*/
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 1, TO_DATE('2016/03/30', 'yyyy/mm/dd'), 3);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 2, TO_DATE('2016/04/01', 'yyyy/mm/dd'), 3);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 3, TO_DATE('2016/04/05', 'yyyy/mm/dd'), 3);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 4, TO_DATE('2016/04/06', 'yyyy/mm/dd'), 3);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 5, TO_DATE('2016/04/07', 'yyyy/mm/dd'), 3);

/*2 GUESTS, SUPERIOR ROOM*/
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 6, TO_DATE('2016/04/08', 'yyyy/mm/dd'), 2);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 7, TO_DATE('2016/04/09', 'yyyy/mm/dd'), 2);

/*1 GUEST, SUPERIOR ROOM*/
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 8, TO_DATE('2016/03/30', 'yyyy/mm/dd'), 1);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 9, TO_DATE('2016/04/01', 'yyyy/mm/dd'), 1);

/*2 GUESTS, DELUXE ROOM*/
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 34, TO_DATE('2016/04/05', 'yyyy/mm/dd'), 2);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 35, TO_DATE('2016/04/06', 'yyyy/mm/dd'), 2);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 36, TO_DATE('2016/04/07', 'yyyy/mm/dd'), 2);

/*1 GUEST, DELUXE ROOM*/
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 37, TO_DATE('2016/04/08', 'yyyy/mm/dd'), 1);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 38, TO_DATE('2016/04/09', 'yyyy/mm/dd'), 1);

/*2 GUESTS, BASIC ROOM*/
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 67, TO_DATE('2016/10/05', 'yyyy/mm/dd'), 2);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 68, TO_DATE('2016/08/19', 'yyyy/mm/dd'), 2);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 69, TO_DATE('2016/04/29', 'yyyy/mm/dd'), 2);

/*1 GUEST, BASIC ROOM*/
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 70, TO_DATE('2016/09/03', 'yyyy/mm/dd'), 1);
INSERT INTO BOOKING (BID, GID, ROOMNUM, CDATE, NOG) 
  VALUES(BOOKING_ID.NEXTVAL, GUEST_ID.NEXTVAL, 71, TO_DATE('2016/12/24', 'yyyy/mm/dd'), 1);

COMMIT

SET TERMOUT ON
PROMPT Demonstration table build is complete.
